version: "3.8"

services:
  user-sys-api-ts:
    image: bananaztech/user-sys-api-ts:latest
    container_name: user-api-ts-prod
    restart: always
    environment:
      DB_PORT: 3306
      DB_HOST: "example.com"
      DB_USER: "Key-API"
      DB_PWD: "example"
      DB_NAME: "keys"
    expose:
      - 4000

networks:
  default:
    external:
      name: frontend
